# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xXjTKNfb3pyXXkCg8xc8JZKiV15spIv4
"""

a = int(input("Введи делимое: "))
b = int(input("Введи делитель: "))

try:
  x = a // b
  print (x)
except ZeroDivisionError:
  print("На 0 делить нельзя!!!")
finally:
  print("Сработал блок файнали")

import random

x = random.randint(0,10)
print(type (x))

import random

arr = [1,2,3,4,5,'test1','test2','test3']
#print ("Случайное значение: ", random.choice(arr))
#print(len(arr))
print(type(arr))

import random
y = random.random()
print(type(y))

x = "Привет"
print(len(x))

import random
y = random.uniform(1.5, 2.5)
print (y)

import random
a = random.randint(1,6)
b = random.randint(1,6)
c = random.randint(1,6)
d = random.randint(1,6)
total = a + b + c + d

print ("Бросок 1 ", a, "Бросок 2 ", b, "Бросок 3 ", c, "Бросок 4 ", d)
print ("Общая сумма ", total)

import random

k = 4
y = []

while k != 0:
  x = random.randint(1,6)
  k -= 1
  y.append(x)
  print (y)

print ("Суммарное значение 4 бросков", sum(y))

import random

k = 4
y = []
total = 0

while k != 0:
  x = random.randint(1,6)
  k -= 1
  y.append(x)
  print (y)

for i in y:
  print ("Значение i: ", "Значение total ", total)
  total += i


print ("Суммарное значение 4 бросков", total)

import random

chars = '+-/*!&$#?=@<>abcdefghijklnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'
length = input('Длинна пароля:' + "\n")
password =""

try: 
  length = int(length)
  for i in range(length):
    password += random.choice(chars)
  print ("Ваш пароль: ", password)
except ValueError:
  print ("Ты ввел не цифры, а буквы или символы. Исправься!")
finally:
  password = ""
  length = input('Длинна пароля:' + "\n") 
  length = int(length)
  for i in range(length):
    password += random.choice(chars)
  print ("Ваш пароль: ", password)